#!/bin/bash

mkdir $1
CWD=$(pwd)
echo "output written to $CWD/$1"
a=`expr 1`
b=`expr 0`


echo "First condition files:"
for i in $*
do
	if [ $i == $1 ]
	then
		a=`expr 2`
	fi
	if [ $a -eq 1 ]
	then
		if [ $i == C ]
		then
			a=`expr 2`
		else
			b=$((b+1))
			echo "	: $i, $b"
			if [ ! -f $i ]; then
				echo "ERROR: File not found!"
				echo "exiting."
				exit 0
			fi
			cd $1
			ln -s ../$i conditionA_$b.prob
			cd ..
		fi
	fi
	if [ $i == $1 ]
	then
		a=`expr 1`
	fi
done
a=`expr 1`
b=`expr 0`
echo "Second condition files:"
for i in $*
do
	if [ $i == C ]
	then
		a=`expr 2`
	fi
	if [ $a -eq 2 ]
	then
		if [ $i != C ]
		then
			b=$((b+1))
			echo "	: $i, $b"
			if [ ! -f $i ]; then
				echo "ERROR: File not found!"
				echo "exiting."
				exit 0
			fi
			cd $1
			ln -s ../$i conditionB_$b.prob
			cd ..
		fi
	fi
done

cd $1
cpThis.bash
echo "computing clusters (output written to $CWD/$1/partitionMerge2.Rout)"
time R CMD BATCH partitionMerge2.R
echo "done!"
echo "Running Reversible Jump using parallel GNU"
time ./parallelGNU.bash
echo "Done!"
echo "Estimates written to $CWD/$1/estimates.txt"

exit 0
